### ISSUE TITLE
Incorrect Display of Username and Message in RefreshChatPage Use Case 

### ISSUE THREAD

**Issue by JoyceQu** [sunyilll/Project_207#18]
When refreshing chat history, the program displays the message in the place where the username is supposed to be and vice versa.

**Comment by JoyceQu** [comment]
The first picture below illustrates our desired display, where usernames appear on the left and messages on the right. However, in the second picture, the actual view after refreshing, the messages are mistakenly on the left instead of the correct placement on the right.
![Refresh_bug_correct_display](https://github.com/sunyilll/Project_207/assets/52988847/59066c7a-6c2b-4d7c-a31c-6f7fbb76e811)
![Refresh_bug_incorrect_display](https://github.com/sunyilll/Project_207/assets/52988847/8247a3c6-e551-46b0-ac93-bffd1d7dd2a3)

**Comment by sunyilll** [comment]
This is fixed now.
